apiVersion: v2
name: dbp-moodle
description: A Helm chart for dBildungsplattform Moodle including customizations
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: moodle
    version: "22.2.7"
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: "19.5.3"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    version: "18.2.2"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: "12.0.0"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: cronjob
    alias: backup-cronjob
    version: 0.1.0
    repository: "file://charts/backup-cronjob"
    condition: backup.enabled

# - name: etherpad-postgresql
#   condition: postgresql.enabled
#   version: "12.1.15"
#   repository: https://charts.bitnami.com/bitnami
# - name: etherpad-lite
# - name: sql-exporter

#Include tasks for sc-serviceaccounts.yml
