#general moodle helm chart values
redisEnabled: true
restore: false
infratools_image_tag: 4.0.3
moodle_pvc_name: moodle-moodle
moodle_pvc_size: 8Gi
moodle_image_tag: 4.1.10-debian-12-r4
moodle_chart_version: 14.3.2

global:
  name: infra
  stage: infra
  namespace: "infra-01"
  kubectl_version: kubernetes_version
  get_kubectl_command: | #This does not work this way sadly
    curl -LO https://dl.k8s.io/release/v{{ .Values.global.kubectl_version }}/bin/linux/amd64/kubectl
    chmod +x kubectl
    mv ./kubectl /usr/local/bin/kubectl

backup: #How to enable the serviceaccounts like we did previously with the tag?
  enabled: {{ include stage-backup-enabled . }}
  backup_gpg_key_names: dbpinfra
  s3_bucket_name: default
  cluster_name: default
  endpoint: https://s3-eu-central-2.ionoscloud.com #s3 region Berlin endpoint


#Horizontal Pod Autoscaling Values
moodle_hpa:
  enabled: false
  # Moodle Autoscaling Values
  min_replicas: 1
  max_replicas: 3
  average_cpu_utilization: 50
  # The up and downscaling values to have more control over the speed moodle will be scaled
  scaledown_value: 25 # The max amount in percent to scale in one step per cooldown period
  scaledown_cooldown: 60
  scaleup_value: 50
  scaleup_cooldown: 15


#redis helm chart values
redis:
  architecture: standalone
  sentinel:
    enabled: false
  auth:
    enabled: true
    existingSecret: moodle
    existingSecretPasswordKey: redis-password
    usePasswordFileFromSecret: true

#mariadb helm chart values 
# mariadb:
#   enabled: true

#postgresql helm chart values 
# postgresql:
#   enabled: true
#   global:
#     storageClass: "nfs-client"
#   image:
#     tag: "{{ moodle_postgresql_image_tag }}"
#   auth:
#     username: "{{ moodle_postgresql_username }}"
#     database: moodle
#     existingSecret: moodle
#     secretKeys:
#       adminPasswordKey: PGSQL_POSTGRES_PASSWORD
#       userPasswordKey: "{{ moodle_db_password_key }}"
#   metrics:
#     enabled: true
#     serviceMonitor:
#       enabled: true
#   primary:
#     extendedConfiguration: |
#       max_connections = 800
#     resources:
#       requests:
#         cpu: "{{ moodle_db_requests_cpu }}"
#         memory: "{{ moodle_db_requests_memory }}"
#       limits:
#         cpu: "{{ moodle_db_limit_cpu }}"
#         memory: "{{ moodle_db_limit_memory }}"
