#general moodle helm chart values
redisEnabled: true
restore: false
moodle_pvc_name: moodle-moodle
moodle_pvc_size: 8Gi
moodle_chart_version: 14.3.2
serviceAccount:
  create: true

backup: #How to enable the serviceaccounts like we did previously with the tag?
  backup_gpg_key_names: dbpinfra
  s3_bucket_name: default
  cluster_name: default
  endpoint: https://s3-eu-central-2.ionoscloud.com #s3 region Berlin endpoint


global:
  name: infra
  stage: infra
  kubectl_version: "1.28.7"
  moodle_image_tag: 4.1.10-debian-12-r5
  infratools_image_tag: 4.0.3

database:
  mariadb:
    enabled: false
    host_name: moodle-mariadb
    values:
      global:
        storageClass: "nfs-client"
      image:
        tag: "11.3.2-debian-12-r5"
      auth:
        username: "moodle"
        database: moodle
        existingSecret: moodle
        rootPassword: "moodle"
        password: "password"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      primary:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 9
            memory: 3Gi

  postgresql:
    enabled: true
    image:
      tag: 14.8.0-debian-11-r0
    auth:
      username: ""
      database: "moodle"
      existingSecret: ""
      secretKeys:
        adminPasswordKey: ""
        userPasswordKey: ""
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true



# Horizontal Pod Autoscaling Values
moodle_hpa:
  enabled: false
  # Moodle Autoscaling Values
  min_replicas: 1
  max_replicas: 3
  average_cpu_utilization: 50
  # The up and downscaling values to have more control over the speed moodle will be scaled
  scaledown_value: 25 # The max amount in percent to scale in one step per cooldown period
  scaledown_cooldown: 60
  scaleup_value: 50
  scaleup_cooldown: 15


#redis helm chart values
redis:
  architecture: standalone
  sentinel:
    enabled: false
  auth:
    enabled: true
    existingSecret: moodle
    existingSecretPasswordKey: redis-password
    usePasswordFileFromSecret: true

tags:
  database: true