apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-hook-role"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
rules: {{- toYaml .Values.dbpMoodle.extended_permissions.rules | nindent 2 }}
