apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-plugins
  namespace: {{ .Release.Namespace }}
data:
  moodle-plugin-list.sh: |
    PLUGINS=(
  {{- range $key, $plugin := .Values.dbpMoodle.plugins.plugin_list }}
    {{- if $plugin.enabled }}
      "{{ $key }}:{{ $plugin.fullname }}:{{ $plugin.install_dir }}"
    {{- end }}
  {{- end }}
    )