apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-update-helper-job-script
  namespace: {{ .Values.global.namespace }}
data:
  {{ .Release.Name }}-update-helper-job-script: |-
{{ tpl ( .Files.Get "scripts/moodleUpdateHelperJobScript.sh" ) . | indent 4 }}