enabled: true
global:
  storageClass: "nfs-client"
image:
  tag: "11.3.2-debian-12-r5"
auth:
  username: "moodle"
  database: "moodle"
  rootPassword: "moodle"
  password: "moodle"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
primary:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 9
      memory: 3Gi
