apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "{{ .Values.moodle_pvc_name }}"
  namespace: "{{ .Values.global.namespace }}"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.moodle_pvc_size }}"