apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-test-cronjob-php
  namespace: {{ .Values.global.namespace }}
data:
  moodle-cronjob-script: |-
{{ tpl ( .Files.Get "scripts/moodleCronjobScript.sh" ) . | nindent 4 }}