{{- if .Values.external_pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    {{- with .Values.external_pvc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: "{{ .Values.external_pvc.name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  storageClassName: "{{ .Values.external_pvc.storage_class }}"
  accessModes:
  {{- if not (empty .Values.external_pvc.accessModes) }}
  {{- range .Values.external_pvc.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.external_pvc.size }}"
{{- end }}