apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  # PGSQL_POSTGRES_PASSWORD: "moodle"
  mariadb-password: "moodle"
  mariadb-root-password: "moodle"
  redis-password: "moodle"
  moodle-password: "password"
  password: "password"
  username: "admin"
  etherpad-postgresql-password: "moodle"
  etherpad-api-key: "moodle"