apiVersion: v1
kind: Secret
type: Opaque
metadata:
  # has to be named same as release, since the bitnami/moodle is hardcoded to read MOODLE_PASSWORD from a secret with the moodles name
  # can be changed after upgrading the chart to 20.2.4
  # moodle/templates/deployment.yaml#173
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  # PGSQL_POSTGRES_PASSWORD: "moodle"
  mariadb-password: "moodle"
  mariadb-root-password: "moodle"
  moodle-password: "password"
  password: "password"
  username: "admin"