{{- if (.Values.backup.enabled) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: moodle-backup-s3
  namespace: "{{ .Release.Namespace }}"
data:
  s3_access_key: {{ .Values.backup.secrets.s3_access_key }}
  s3_access_secret: {{ .Values.backup.secrets.s3_access_secret }}
  s3_endpoint_url: {{ .Values.backup.secrets.s3_endpoint_url }}
{{- end }}