{{- if not .Values.dbpMoodle.secrets.useExistingSecret }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  moodle-password: {{ include "dbpMoodle.secrets.moodle_password" . }}
  {{- if .Values.postgresql.enabled }}
  PGSQL_POSTGRES_PASSWORD: {{ include "dbpMoodle.secrets.postgres_password" . }}
  {{- end }}
  mariadb-password: {{ include "dbpMoodle.secrets.mariadb_password" . }}
  mariadb-root-password: {{ include "dbpMoodle.secrets.mariadb_root_password" . }}
  {{- if .Values.redis.enabled }}
  redis-password: "moodle"
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: {{ include "dbpMoodle.secrets.etherpad_postgresql_password" . }}
  etherpad-api-key: {{ include "dbpMoodle.secrets.etherpad_api_key" . }}
  {{- end }}
{{- end }}