apiVersion: v1
kind: Secret
type: Opaque
metadata:
  # has to be named same as release, since the secret name for moodle-password is hardcoded to moodles name in bitnami/moodle
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  PGSQL_POSTGRES_PASSWORD: "moodle"
  mariadb-password: "moodle"
  mariadb-root-password: "moodle"
  moodle-password: "password"
  password: "password"
  username: "admin"