apiVersion: v1
kind: Secret
type: Opaque
metadata:
  # has to be named same as release, since the bitnami/moodle is hardcoded to read MOODLE_PASSWORD from a secret with the moodles name
  # can be changed after upgrading the chart to 20.2.4
  # moodle/templates/deployment.yaml#173
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- if .Values.postgresql.enabled }}
  PGSQL_POSTGRES_PASSWORD: "moodle"
  {{- end }}
  mariadb-password: "moodle"
  mariadb-root-password: "moodle"
  {{- if .Values.postgresql.enabled }}
  postgresql-password: "moodle"
  {{- end }}
  moodle-password: "password"
  password: "password"
  username: "admin"
  {{- if .Values.redis.enabled }}
  redis-password: "moodle"
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: "moodle"
  etherpad-api-key: "moodle"
  {{- end }}