apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{- if .Values.postgresql.enabled }}
  PGSQL_POSTGRES_PASSWORD: "moodle"
  {{- end }}
  mariadb-password: "moodle"
  mariadb-root-password: "moodle"
  {{- if .Values.postgresql.enabled }}
  postgresql-password: "moodle"
  {{- end }}
  moodle-password: "password"
  password: "password"
  username: "admin"
  {{- if .Values.redis.enabled }}
  redis-password: "moodle"
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: "moodle"
  etherpad-api-key: "moodle"
  {{- end }}