---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-debian-11-r[0-9]+'
jobs:
  build_and_push:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/build-and-push.yaml@master
    with:
      registry: ghcr.io
      image: dbildungsplattform/moodle
      tag: ${{ github.ref_name }}
