---
name: BAP Docker Image on Tag

on:
  push:
    tags:
      - 'moodle-[0-9]+.[0-9]+.[0-9]+-debian-11-r[0-9]+'
jobs:
  build_and_push:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/bap.yaml@DBP-36-custom-image-build-moodle
    with:
      registry: ghcr
