---
name: BAP Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-debian-11-r[0-9]+'
jobs:
  build_and_push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      registry: ghcr.io
      image: dbildungsplattform/moodle
      tag: ${{ github.ref_name }}
