# https://github.com/terraform-docs/gh-actions

name: Generate Helm-Docs on Pull Request
on:
  push:
    branches:
      - 'DBP-000-Generate_Helm_Doc_On_PR'
  pull_request:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/workflows/**'
      - '.github/templates/**'

jobs:
  create_helm-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checking out code to Runner
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Generate Helm-Docs
      uses: hpi-schul-cloud/infra-tools/.github/actions/helm-docs@tf-helm-docs-v1
      with:
        # provide name of dirs to run helm-docs on, separate by comma without space
        src_path: "charts"
        template_file: ".github/templates/README.md.gotmpl"
        # provide name of dirs to ignore, separate by comma without space
        # ignored_dirs: 
        git_push: true
        username: "devops"
        email: "devops@dbildungsplattform.de"