---
name: Moodle Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master

jobs:
  build_image_on_push:
    uses: hpi-schul-cloud/infra-tools/.github/workflows/imagetoghcr-on-push.yaml@master
    with:
      image_name: "moodle"
