---
name: Moodle Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - master

jobs:
  build_image_on_push:
    permissions:
      packages: write
    uses: hpi-schul-cloud/infra-tools/.github/workflows/imagetoghcr-on-push.yaml@DBP-36-custom-image-build-moodle
    with:
      image_name: "moodle"
